### ISSUE TITLE
ddetiab in multideterminant

### ISSUE THREAD

**Issue by neelravi** [filippi-claudia/champ#226]
When debug mode is enabled, the following out-of-bound array error is thrown:

How to reproduce:
1) compile in debug mode
2) Run the test case of butadiene 500 determinants.

forrtl: severe (408): fort: (2): Subscript #1 of the array DDETIAB has value 175 which is greater than the upper bound of 174

Image              PC                Routine            Line        Source             
vmc.mov1           0000000000F5175F  Unknown               Unknown  Unknown
vmc.mov1           00000000009725A0  multideterminant_         186  multideterminant.f
vmc.mov1           0000000000CE0C8E  hpsi_mod_mp_hpsi_         139  hpsi.f
vmc.mov1           000000000042D917  acuest_mod_mp_acu         278  acuest.f
vmc.mov1           0000000000533C72  vmc_f_mod_mp_vmc_         113  vmc.f
vmc.mov1           00000000005685FF  optwf_mod_mp_optw          38  optwf.f90
vmc.mov1           000000000055DE7E  MAIN__                     94  main.f90
vmc.mov1           0000000000413362  Unknown               Unknown  Unknown
libc.so.6          00007F48DB201D90  Unknown               Unknown  Unknown
libc.so.6          00007F48DB201E40  __libc_start_main     Unknown  Unknown
vmc.mov1           0000000000413265  Unknown               Unknown  Unknown

**Comment by josuelandinez** [comment]
Closing, the issue it was solved properly some months ago.
