### ISSUE TITLE
Default Intel Compiler Flags for AMD Zen4 are wrong

### ISSUE THREAD

**Issue by NicoMittenzwey** [filippi-claudia/champ#270]
In CMakeModules/FindSIMD.cmake the Fortran_FLAGS are set to "-xCORE-AVX512" when using "cmake -H. -Bbuild -D CMAKE_Fortran_COMPILER=mpiifort" regardless of the underlying architecture. This produces binaries which do not work on AMD Zen4 CPUs. For the later it should be "-axCORE-AVX512".

**Comment by filippi-claudia** [comment]
Dear Ravindra, will the cmake figure out the architecture or do we have do give additional flags? If the latter is the case, can you please update the README? Thanks, Claudia

**Comment by neelravi** [comment]
@filippi-claudia Cmake will figure out automatically which flags to include. README need not change in this case.
